services:
  app:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 099Rast-Nertes
      POSTGRES_DB: check_in
    ports:
      - "5432:5432"