services:
  app:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - .env.docker
    ports:
      - "5432:5432"