"""Initial migration

Revision ID: 66592dd3db45
Revises: 
Create Date: 2025-05-23 00:44:28.697277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66592dd3db45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reasons', 'status',
               existing_type=sa.Enum('CONFIRMED', 'PENDING', 'REJECTED', name='statusenum'),
               type_=postgresql.ENUM('CONFIRMED', 'PENDING', 'REJECTED', name='status_type'),
               existing_nullable=True)
    op.alter_column('reasons', 'reason_name',
               existing_type=sa.Enum('ILLNESS', 'GOOD_REASON', 'OTHER', name='reasonnameenum'),
               type_=postgresql.ENUM('ILLNESS', 'GOOD_REASON', 'OTHER', name='reason_name_type'),
               existing_nullable=True)
    op.create_index(op.f('idx_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.create_index(op.f('idx_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendances_reason_id'), 'attendances', ['reason_id'], unique=False)
    op.create_index(op.f('idx_attendances_lesson_id'), 'attendances', ['lesson_id'], unique=False)
    # ### end Alembic commands ###
