"""Set not null constraints

Revision ID: 80848e890f19
Revises: 66592dd3db45
Create Date: 2025-05-24 19:00:28.554401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80848e890f19'
down_revision: Union[str, None] = '66592dd3db45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'attendance',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('attendances', 'missed_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'lesson_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('attendances', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('attendances', 'reason_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('attendances', 'is_qr',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_attendances_lesson_id'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_reason_id'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_user_id'), table_name='attendances')
    op.alter_column('groups', 'lessons_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'lesson_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lessons', 'lesson_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('lessons', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('idx_lessons_group_id'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_teacher_id'), table_name='lessons')
    op.alter_column('reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'total_attended',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_headman',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_headman',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_attended',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('reasons', 'status',
               existing_type=sa.Enum('CONFIRMED', 'PENDING', 'REJECTED', name='statusenum'),
               type_=postgresql.ENUM('CONFIRMED', 'PENDING', 'REJECTED', name='status_type'),
               nullable=True)
    op.alter_column('reasons', 'reason_name',
               existing_type=sa.Enum('ILLNESS', 'GOOD_REASON', 'OTHER', name='reasonnameenum'),
               type_=postgresql.ENUM('ILLNESS', 'GOOD_REASON', 'OTHER', name='reason_name_type'),
               nullable=True)
    op.alter_column('reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.alter_column('lessons', 'teacher_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('lessons', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('lessons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'lesson_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('lessons', 'lesson_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'lessons_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendances_reason_id'), 'attendances', ['reason_id'], unique=False)
    op.create_index(op.f('idx_attendances_lesson_id'), 'attendances', ['lesson_id'], unique=False)
    op.alter_column('attendances', 'is_qr',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('attendances', 'reason_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('attendances', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('attendances', 'lesson_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'missed_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendances', 'attendance',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
