"""поле teacher_comment

Revision ID: a46c50df0eee
Revises: 8f2a34dead15
Create Date: 2025-07-04 17:34:29.344045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46c50df0eee'
down_revision: Union[str, None] = '8f2a34dead15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=True)
    op.add_column('reasons', sa.Column('student_comment', sa.Text(), nullable=True))
    op.add_column('reasons', sa.Column('teacher_comment', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_reasons_id'), table_name='reasons')
    op.create_index(op.f('ix_reasons_id'), 'reasons', ['id'], unique=True)
    op.drop_column('reasons', 'comment')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'is_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('reasons', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reasons_id'), table_name='reasons')
    op.create_index(op.f('ix_reasons_id'), 'reasons', ['id'], unique=False)
    op.drop_column('reasons', 'teacher_comment')
    op.drop_column('reasons', 'student_comment')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    # ### end Alembic commands ###
