"""поле comment

Revision ID: c85e9550db1d
Revises: a46c50df0eee
Create Date: 2025-07-04 18:17:32.249793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85e9550db1d'
down_revision: Union[str, None] = 'a46c50df0eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons', sa.Column('comment', sa.Text(), nullable=True))
    op.drop_column('reasons', 'teacher_comment')
    op.drop_column('reasons', 'student_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons', sa.Column('student_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reasons', sa.Column('teacher_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reasons', 'comment')
    # ### end Alembic commands ###
